version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.0.2
workflows:
  node-tests:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/todo-back
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_DB: tododb_test
          POSTGRES_PASSWORD: password
          PSQL_USERNAME: postgres
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Create db
          command: npm run db:create
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: test
          command: npm test --collectCoverage=true
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov > ./coverage/coverage.lcov'
      - codecov/upload:
          file: ./coverage/coverage.lcov
          token: e9dd6d3f-c3ab-4756-87ee-67f1935d3397
      - store_artifacts:
          path: coverage.lcov
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: ./coverage/coverage.lcov

